/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prestamofausto;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author edgar
 */
public class MantPrestamos extends javax.swing.JFrame {
        Date fechaActual = new Date();
    /**
     * Creates new form MantPrestamos
     */
    public MantPrestamos() {
        initComponents();setLocationRelativeTo(null);
            setResizable(false);
         this.getContentPane().setBackground(Color.WHITE);
        
        fecha_inicio.setDate(fechaActual);
        fecha_final.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        id_cliente = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        id_fiador = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        estado = new javax.swing.JCheckBox();
        fecha_inicio = new com.toedter.calendar.JDateChooser();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        plazo = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        fecha_final = new com.toedter.calendar.JDateChooser();
        jLabel24 = new javax.swing.JLabel();
        garantia = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        monto = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        balance = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        taza = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        cuota = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        foto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 153, 255));
        jLabel1.setText("MANTENIMIENTO PRESTAMO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 153, 255));
        jLabel17.setText("ID:");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idKeyReleased(evt);
            }
        });
        getContentPane().add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 142, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 153, 255));
        jLabel18.setText("Id cliente");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));
        getContentPane().add(id_cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 142, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 153, 255));
        jLabel19.setText("Id fiador");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));
        getContentPane().add(id_fiador, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 142, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 153, 255));
        jLabel20.setText("Estado");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));
        getContentPane().add(estado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 130, -1));
        getContentPane().add(fecha_inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 120, 30));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 153, 255));
        jLabel21.setText("Plazo");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, -1, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 153, 255));
        jLabel22.setText("Fecha inicio");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        plazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plazoActionPerformed(evt);
            }
        });
        plazo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                plazoKeyReleased(evt);
            }
        });
        getContentPane().add(plazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 142, -1));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 153, 255));
        jLabel23.setText("Fecha final");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));
        getContentPane().add(fecha_final, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 140, -1));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 153, 255));
        jLabel24.setText("Tipo garantia");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));
        getContentPane().add(garantia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 142, 30));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 153, 255));
        jLabel25.setText("Monto");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, -1, 30));

        monto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                montoActionPerformed(evt);
            }
        });
        monto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                montoKeyReleased(evt);
            }
        });
        getContentPane().add(monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 142, 30));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 153, 255));
        jLabel26.setText("Balance");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, 30));
        getContentPane().add(balance, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 142, 20));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 153, 255));
        jLabel27.setText("Taza");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 120, -1, 30));

        taza.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tazaKeyReleased(evt);
            }
        });
        getContentPane().add(taza, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 142, 20));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 153, 255));
        jLabel28.setText("Cuota");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, 30));

        cuota.setEditable(false);
        getContentPane().add(cuota, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 142, 30));

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 153, 255));
        jLabel29.setText("Foto");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 190, -1, 30));
        getContentPane().add(foto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 160, 30));

        jButton1.setBackground(new java.awt.Color(51, 153, 255));
        jButton1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 350, 150, 50));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_prestamo_cuota", "Num_cuota", "Fecha cuota", "Valor cuota", "Valor amortizacion", "Valor interes"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 710, 250));

        jButton2.setBackground(new java.awt.Color(51, 153, 255));
        jButton2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 150, 50));

        jButton3.setBackground(new java.awt.Color(51, 153, 255));
        jButton3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("VOLVER");
        jButton3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 10, 130, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void plazoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_plazoKeyReleased
       if(plazo.getText().equals("")){
          fecha_inicio.setDate(fechaActual);
          return;
       }
      
      Calendar calendario = Calendar.getInstance();
      calendario.setTime(fecha_inicio.getDate());
      calendario.add(calendario.MONTH, Integer.parseInt(plazo.getText()));
      fecha_final.setDate(calendario.getTime());
    }//GEN-LAST:event_plazoKeyReleased

    private void plazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plazoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_plazoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      MetodosGenerales metodos = new MetodosGenerales ();
      SimpleDateFormat fomato_fecha = new SimpleDateFormat("MM/dd/YYYY");
      String fecha_Inicio = fomato_fecha.format(fecha_inicio.getCalendar().getTime());
      String fecha_Final = fomato_fecha.format(fecha_final.getCalendar().getTime());
      String estadoString = estado.isSelected() ? "True" : "False";
      String datos =id.getText()+"~"+id_cliente.getText()+"~"+id_fiador.getText()+"~"+estadoString+"~"+fecha_Inicio+"~"+plazo.getText()+"~"+fecha_Final+"~"+garantia.getText()+"~"+monto.getText()+"~"+balance.getText()+"~"+taza.getText()+"~"+cuota.getText()+"~"+foto.getText();
      metodos.registrar("Prestamos.txt", datos);
      JOptionPane.showMessageDialog(null,"Se ha registrado correctamente.");

      int plazoInteger = Integer.parseInt(plazo.getText());
    
       Calendar calendario = Calendar.getInstance();
       Date fecha = fecha_inicio.getDate();
       calendario.setTime(fecha);
       
       DecimalFormat df = new DecimalFormat("#.00");
       
       double montoPrestamo = Double.parseDouble(monto.getText());
       double valor_interes = ( montoPrestamo * Integer.parseInt(taza.getText()) / 100 );
       double valorCuota  = ( Integer.parseInt(monto.getText())  / Integer.parseInt(plazo.getText()) )  + valor_interes;
       double valorAutomizacion = valorCuota - valor_interes;
       
      for(int i=1;i<=plazoInteger;i++){
         String fechaCuota = fomato_fecha.format(calendario.getTime());
         String datosCuotas =id.getText()+"~"+String.valueOf(i)+"~"+id_cliente.getText()+"~"+fechaCuota+"~"+df.format(valorCuota)+"~"+df.format(valorAutomizacion)+"~"+df.format(valor_interes)+"~"+"false";
         metodos.registrar("Cuotas_Prestamos.txt", datosCuotas);
         calendario.add(calendario.MONTH, 1);
         
         montoPrestamo -=valorAutomizacion;
         valor_interes = Math.abs( (montoPrestamo * Integer.parseInt(taza.getText()) / 100 ));
         valorAutomizacion = valorCuota - valor_interes;
         
         
//         try{
//                FileOutputStream archivo = new   FileOutputStream (id.getText()+i+".pdf");
//                Document doc = new Document();
//                PdfWriter.getInstance(doc, archivo);
//                doc.open();
//                String contenido="Numero cuota:"+i+" \r\n valor cuota: " + valorCuota;
//
//                doc.add(metodos.encabezado("Prestamo en la fecha " + fecha.getDate()));
//                doc.add(metodos.informacion("infomacion 2 "));
//                doc.add(metodos.pie("pie"));
//                doc.add(new Paragraph (contenido));
//                doc.close();
//
//            }catch(FileNotFoundException | DocumentException ex){
//
//            }

     }
      
      
      
    }//GEN-LAST:event_jButton1ActionPerformed

    private void idKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyReleased
    

    }//GEN-LAST:event_idKeyReleased

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new MenuPrincipal().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void montoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_montoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_montoActionPerformed

    private void montoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_montoKeyReleased
      
       
    }//GEN-LAST:event_montoKeyReleased

    private void tazaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tazaKeyReleased
        try{
            if(taza.getText().equals("")==false){
            int valor_interes = ( Integer.parseInt(monto.getText()) * Integer.parseInt(taza.getText()) / 100 );
            int valorCuota  = ( Integer.parseInt(monto.getText())  / Integer.parseInt(plazo.getText()) )  + valor_interes;
                cuota.setText(String.valueOf(valorCuota));
        }
            
        }catch(Exception e){
        }
        
        
    }//GEN-LAST:event_tazaKeyReleased

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantPrestamos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField balance;
    private javax.swing.JTextField cuota;
    private javax.swing.JCheckBox estado;
    private com.toedter.calendar.JDateChooser fecha_final;
    private com.toedter.calendar.JDateChooser fecha_inicio;
    private javax.swing.JTextField foto;
    private javax.swing.JTextField garantia;
    private javax.swing.JTextField id;
    private javax.swing.JTextField id_cliente;
    private javax.swing.JTextField id_fiador;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField monto;
    private javax.swing.JTextField plazo;
    private javax.swing.JTextField taza;
    // End of variables declaration//GEN-END:variables
}
