/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prestamofausto;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edgar
 */
public class MovimientoCobro extends javax.swing.JFrame {

    /**
     * Creates new form MovimientoCobro
     */
    
    public MovimientoCobro() {
        initComponents();
            Date fechaActual = new Date();
            fecha.setDate(fechaActual);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mensaje = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        Id = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        fecha = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        Cliente = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        Valor = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cuotasCliente = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mensaje.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        mensaje.setText("CREANDO");

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setText("ID:");

        Id.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdActionPerformed(evt);
            }
        });
        Id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                IdKeyReleased(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setText("Fecha:");

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setText("Cliente:");

        Cliente.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Cliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ClienteKeyReleased(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setText("Valor:");

        Valor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Valor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValorActionPerformed(evt);
            }
        });

        jButton1.setText("Guardar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cuotasCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        cuotasCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID prestamo", "Num cuota", "Fecha", "Valor cuota", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(cuotasCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Valor, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                                    .addComponent(Cliente)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(mensaje))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel19)))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mensaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(Id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdActionPerformed

    private void IdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdKeyReleased
        MetodosGenerales usuario= new MetodosGenerales();
        String consulta=usuario.validarID("EncabezadoCuotas.txt", Id.getText());
        if(consulta.equals("no")){
            Date fechaHoy = new Date();
            fecha.setDate(fechaHoy);
            Cliente.setText("");
            Valor.setText("");
            mensaje.setText("CREANDO");
        }else{
            Date fecha_entrada = new Date(consulta.split("~")[1]);
            fecha.setDate(fecha_entrada);
            Cliente.setText(consulta.split("~")[2]);
            Valor.setText(consulta.split("~")[3]);
            mensaje.setText("Modificando");
        }
    }//GEN-LAST:event_IdKeyReleased

    private void ClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ClienteKeyReleased
        DefaultTableModel  modelo =(DefaultTableModel) cuotasCliente.getModel();
        modelo.setRowCount(0);
        cuotasCliente.setModel(modelo);
        if(Cliente.getText().equals("")){
            return;
        }

        MetodosGenerales general = new MetodosGenerales ();
        ArrayList<String> vector = new ArrayList();

        String dato_cliente = general.validarID("Clientes.txt",Cliente.getText());
        if(dato_cliente.equals("no")){
            JOptionPane.showMessageDialog(null,"Error el cliente no existe","Error",JOptionPane.ERROR_MESSAGE);
            return;

        }
//        else if(dato_cliente.split("~")[9].equals("true")==false || dato_cliente.split("~")[10].equals("Socio Activo")==false){
//            JOptionPane.showMessageDialog(null,"Error el cliente debe ser un socio activo y tener el status en true","Error",JOptionPane.ERROR_MESSAGE);
//            return;
//        }
        vector=general.LlenarTablaCondicion("Cuotas_Prestamos.txt",2,Cliente.getText());
        String datos [ ] = new String [5];
        if(vector.size()<1){
            JOptionPane.showMessageDialog(null,"Error el cliente no existe en el archivo cuotas prestamos","Error",JOptionPane.ERROR_MESSAGE);

        }
        
          SimpleDateFormat formato = new SimpleDateFormat("MM/dd/YYYY");
            String fechaD=formato.format(fecha.getCalendar().getTime());
            Date fechaActual = new Date(fechaD);
              
        for (int i = 0; i <vector.size(); i++) {
             Date fechaCuota = new Date(vector.get(i).split("~")[3]);
            if(fechaActual.after(fechaCuota)){
                datos[0]=vector.get(i).split("~")[0];
                datos[1]=vector.get(i).split("~")[1];
                datos[2]=vector.get(i).split("~")[3];
                datos[3]=vector.get(i).split("~")[4];
                datos[4]=vector.get(i).split("~")[7];
                modelo.addRow(datos);
            }

        }
    }//GEN-LAST:event_ClienteKeyReleased

    private void ValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValorActionPerformed

    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(Id.getText().equals("")==false && fecha.getCalendar()!=null && Cliente.getText().equals("")==false && Valor.getText().equals("")==false ){
            MetodosGenerales general = new MetodosGenerales ();
            String validar=general.validarID("Cobros_prestamos.txt",Id.getText());
            SimpleDateFormat fomato_fecha = new SimpleDateFormat("MM/dd/YYYY");
            String fechaCuota = fomato_fecha.format(fecha.getCalendar().getTime());

            if(validar.equals("no")){
                if(cuotasCliente.getRowCount()==0){
                    JOptionPane.showMessageDialog(null,"La tabla de cuotas esta vacia, por favor llenarlo","Error",JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                general.registrar("Cobros_prestamos.txt",Id.getText()+"~"+fechaCuota+"~"+Cliente.getText()+"~"+Valor.getText()+"~"+"false");
                Double abono = Double.parseDouble(Valor.getText());
                 for(int i=0;i<cuotasCliente.getRowCount();i++){
                      String valorCuota = "";
                        Double ValorCuota = Double.parseDouble(cuotasCliente.getValueAt(i, 3).toString());
                        if(abono>=ValorCuota){
                            valorCuota = ValorCuota.toString();
                            abono-=ValorCuota;
                         int secuencia = i+1;
                        general.registrar("Detalles_Cobros.txt",Id.getText()+"~"+secuencia+"~"+cuotasCliente.getValueAt(i, 0).toString()+"~"+cuotasCliente.getValueAt(i, 1).toString()+"~"+valorCuota+"~"+"0"+"~"+"0"+"~"+"0");
                           
                        String validarCuota=general.verificarCuotaTrue(cuotasCliente.getValueAt(i, 0).toString(),cuotasCliente.getValueAt(i, 1).toString());
                            System.out.println(validarCuota);
                        if(validarCuota.equals("no")==false){
                            validarCuota = validarCuota.split("~")[0]+"~"+validarCuota.split("~")[1]+"~"+validarCuota.split("~")[2]+"~"+validarCuota.split("~")[3]+"~"+validarCuota.split("~")[4]+"~"+validarCuota.split("~")[5]+"~"+validarCuota.split("~")[6]+"~"+"false"; 
                            System.out.println(validarCuota);
                            general.modificar("Cuotas_Prestamos.txt", validarCuota.split("~")[0], validarCuota);
                        
                        }
                          if(abono<=0.0){
                            break;
                        }
                        }else{
                            JOptionPane.showMessageDialog(null,"Sobran: "+abono);
                             break;
                        }
                      
                       
                 }
                 
                 
                Id.setText("");
                fecha.setDate(null);
                Cliente.setText("");
                Valor.setText("");
                mensaje.setText("CREANDO");
                DefaultTableModel  modelo =(DefaultTableModel) cuotasCliente.getModel();
                modelo.setRowCount(0);
                cuotasCliente.setModel(modelo);

            }else{
                general.modificar("Detalles_Cobros.txt",Id.getText(),Id.getText()+"~"+fomato_fecha+"~"+Cliente.getText()+"~"+Valor.getText()+"~"+"false");
            }
        }else{
            JOptionPane.showMessageDialog(null,"Todos los campos son obligatorios, por favor llenarlo","Errro",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MovimientoCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MovimientoCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MovimientoCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MovimientoCobro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MovimientoCobro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Cliente;
    private javax.swing.JTextField Id;
    private javax.swing.JTextField Valor;
    private javax.swing.JTable cuotasCliente;
    private com.toedter.calendar.JDateChooser fecha;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mensaje;
    // End of variables declaration//GEN-END:variables
}
